name: llama_traffic_conda
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - absl-py=1.4.0=py310h06a4308_0
  - aiohttp=3.8.3=py310h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - arrow-cpp=11.0.0=py310h7516544_0
  - asttokens=2.4.0=pyhd8ed1ab_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.2=py310h06a4308_0
  - attrs=22.1.0=py310h06a4308_0
  - aws-c-common=0.4.57=he6710b0_1
  - aws-c-event-stream=0.1.6=h2531618_5
  - aws-checksums=0.1.9=he6710b0_0
  - aws-sdk-cpp=1.8.185=hce553d0_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - blas=1.0=mkl
  - blinker=1.4=py310h06a4308_0
  - boost-cpp=1.73.0=h7f8727e_12
  - bottleneck=1.3.5=py310ha9d4c09_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2023.08.22=h06a4308_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2023.7.22=py310h06a4308_0
  - cffi=1.15.1=py310h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py310h06a4308_0
  - comm=0.1.4=pyhd8ed1ab_0
  - contourpy=1.0.5=py310hdb19cb5_0
  - cryptography=41.0.3=py310h130f0dd_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - datasets=2.12.0=py310h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py310h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - dill=0.3.6=py310h06a4308_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=h6a678d5_0
  - filelock=3.9.0=py310h06a4308_0
  - flatbuffers=2.0.0=h2531618_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.3.3=py310h5eee18b_0
  - fsspec=2023.4.0=py310h06a4308_0
  - gast=0.4.0=pyhd3eb1b0_0
  - gflags=2.2.2=he6710b0_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - glog=0.5.0=h2531618_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpc-cpp=1.46.1=h33aed49_1
  - grpcio=1.42.0=py310hce63b2e_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h5py=3.9.0=py310he06866b_0
  - hdf5=1.12.1=h70be1eb_2
  - huggingface_hub=0.15.1=py310h06a4308_0
  - icu=58.2=he6710b0_3
  - idna=3.4=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - ipykernel=6.25.2=pyh2140261_0
  - ipython=8.15.0=pyh0d859eb_0
  - jedi=0.19.0=pyhd8ed1ab_0
  - jinja2=3.1.2=py310h06a4308_0
  - joblib=1.2.0=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.3.1=py310hff52083_0
  - keras=2.11.0=py310h06a4308_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.4.4=py310h6a678d5_0
  - krb5=1.19.4=h568e23c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libboost=1.73.0=h28710b8_12
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang13=14.0.6=default_he11475f_1
  - libcurl=8.1.1=h91b91d3_0
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libllvm14=14.0.6=hdb19cb5_3
  - libnghttp2=1.52.0=ha637b67_1
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.9=h16c4e8d_3
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=h0d84882_2
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hcbfbd50_0
  - libxslt=1.1.37=h2085143_0
  - lz4-c=1.9.4=h6a678d5_0
  - markdown=3.4.1=py310h06a4308_0
  - markupsafe=2.1.1=py310h7f8727e_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46343
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.6=py310h1128e8f_1
  - mkl_random=1.2.2=py310h1128e8f_1
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - multidict=6.0.2=py310h5eee18b_0
  - multiprocess=0.70.14=py310h06a4308_0
  - munkres=1.1.4=py_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - networkx=3.1=py310h06a4308_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.8.4=py310h85018f9_1
  - oauthlib=3.2.2=py310h06a4308_0
  - openssl=1.1.1w=h7f8727e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - orc=1.7.4=hb3bc3d3_1
  - packaging=23.0=py310h06a4308_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.2.1=py310h06a4308_0
  - platformdirs=3.10.0=pyhd8ed1ab_0
  - ply=3.11=py310h06a4308_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.0=py310h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyjwt=2.4.0=py310h06a4308_0
  - pyopenssl=23.2.0=py310h06a4308_0
  - pyparsing=3.0.9=py310h06a4308_0
  - pyqt=5.15.7=py310h6a678d5_1
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.13=h7a1cb2a_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-flatbuffers=2.0=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py310h5eee18b_1
  - python_abi=3.10=2_cp310
  - pytorch=2.0.1=cpu_py310hdc00b08_0
  - pytz=2022.7=py310h06a4308_0
  - pyyaml=6.0=py310h5eee18b_1
  - pyzmq=25.1.0=py310h6a678d5_0
  - qt-main=5.15.2=h8373d8f_8
  - qt-webengine=5.15.9=h9ab4d14_7
  - qtwebkit=5.212=h3fafdc1_5
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - regex=2022.7.9=py310h5eee18b_0
  - requests=2.31.0=py310h06a4308_0
  - requests-oauthlib=1.3.0=py_0
  - responses=0.13.3=pyhd3eb1b0_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - sacremoses=0.0.43=pyhd3eb1b0_0
  - sentencepiece=0.1.99=py310hdb19cb5_0
  - sip=6.6.2=py310h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h295c915_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.11.1=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard=2.11.0=py310h06a4308_0
  - tensorboard-data-server=0.6.1=py310h52d8a92_0
  - tensorboard-plugin-wit=1.8.1=py310h06a4308_0
  - tensorflow=2.11.0=mkl_py310hb40ee82_0
  - tensorflow-base=2.11.0=mkl_py310he5f8e37_0
  - tensorflow-estimator=2.11.0=py310h06a4308_0
  - termcolor=2.1.0=py310h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - tokenizers=0.13.2=py310he7d60b5_1
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.1=py310h5764c6d_3
  - tqdm=4.65.0=py310h2f386ee_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - transformers=4.29.2=py310h06a4308_0
  - typing-extensions=4.7.1=py310h06a4308_0
  - typing_extensions=4.7.1=py310h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.16=py310h06a4308_0
  - utf8proc=2.6.1=h27cfd23_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - werkzeug=2.2.3=py310h06a4308_0
  - wheel=0.38.4=py310h06a4308_0
  - wrapt=1.14.1=py310h5eee18b_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.8.1=py310h5eee18b_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - array-record==0.4.1
      - cloudpickle==2.2.1
      - dacite==1.8.1
      - dask==2023.3.1
      - dataclass-array==1.5.1
      - dm-tree==0.1.8
      - einops==0.6.1
      - einsum==0.3.0
      - etils==1.4.1
      - google-auth==2.16.2
      - googleapis-common-protos==1.60.0
      - imageio==2.31.3
      - immutabledict==2.2.0
      - importlib-resources==6.0.1
      - lark==1.1.7
      - lazy-loader==0.3
      - libclang==16.0.6
      - locket==1.0.0
      - matplotlib==3.6.1
      - numpy==1.21.5
      - openexr==1.3.9
      - pandas==1.5.3
      - partd==1.4.0
      - pillow==9.2.0
      - plotly==5.13.1
      - promise==2.3
      - protobuf==3.19.6
      - pyarrow==10.0.0
      - pyqt5-sip==12.11.0
      - pywavelets==1.4.1
      - scikit-image==0.20.0
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - setuptools==67.6.0
      - tenacity==8.2.3
      - tensorflow-addons==0.21.0
      - tensorflow-datasets==4.9.0
      - tensorflow-graphics==2021.12.3
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorflow-metadata==1.13.0
      - tensorflow-probability==0.19.0
      - threadpoolctl==3.2.0
      - tifffile==2023.8.30
      - toolz==0.12.0
      - trimesh==3.23.5
      - typeguard==2.13.3
      - visu3d==1.5.1
      - waymo-open-dataset-tf-2-11-0==1.6.0
      - zipp==3.16.2
prefix: /home/pmueller/miniconda3/envs/llama_traffic_conda
